### ISSUE TITLE
Compatibility with ggraph

### ISSUE THREAD

**Issue by mschubert** [saezlab/OmnipathR#13]
Nice to see this as an R package as well! :+1:

It looks like the current version does not play nice with `ggraph` (related: https://github.com/thomasp85/ggraph/issues/214; in fact, the code example is taken from working with `OmnipathR` and `ggraph`):

```r
library(ggraph)
library(tidygraph)

net = OmnipathR::import_AllInteractions() %>%
    OmnipathR::interaction_graph() %>%
    as_tbl_graph() %>%
    activate(nodes) %>%
    filter(name == "TP53")

ggraph(net)
```

**Comment by alberto-valdeolivas** [comment]
Hello Michael,

Many thanks for your feedback. 

The problem is in the `ggraph` function itself and it is closely related to the issue you shared. 

In your example, `net` is  a `tbl_graph` object with 1 node (TP53) and 0 edges, although with 13 defined variables (13 columns) for the edges. It seems that the function `ggprah`, as explained in the issue you posted, fails when the graph has no edges. There are no errors when dealing when plotting a normal igraph object:

```
library(ggraph)
library(tidygraph)

net = OmnipathR::import_AllInteractions() %>%
  OmnipathR::interaction_graph() %>%
  as_tbl_graph()  %>%
  activate(nodes)  %>%
  activate(nodes) %>%
  filter(name == "TP53")

as.igraph(net)
plot(as.igraph(net))
```

Best regards,
Alberto.
