### ISSUE TITLE
Omnipath database update

### ISSUE THREAD

**Issue by hallba** [saezlab/OmnipathR#14]
As of 25/2/20 the PPI database (http://omnipathdb.org/interactions?fields=sources&fields=references&genesymbols=1) was substantially updated. In the update several new interactions were added, changing the networks that can be generated. 

Notably, this includes new self interactions that hadn't been present in prior versions of the database. Checking some of the associated PMIDs these may have been introduced unintentionally as the papers do not clearly show self activation through oligomerisation

One example is MAP3K5, which is noted as self interacting with the PMID 11920685. This paper however discusses trans-phosphorylation within the oligomer in response to a phosphorylation induced conformational change. This isn't clearly a PPI, and I'm not sure this is correct. 

Are these changes intentional?

**Comment by alberto-valdeolivas** [comment]
Hello @hallba,

A major update of the webserver was performed during the days you mentioned. I paste here the reply of @deeenes, who is in charge of the pypayh module which feeds the webserver, to my questions about similar issues.  

- **Loop interactions:** we have a 2-3k of them, previously we disabled loops by default but now in pypath.core.network.Network they are enabled. I will modify the code of the server to omit them unless the user asks for them by a new parameter.

- **Duplicates**: the duplicates are exactly due to the loops, in case of mutual interactions we need to write 2 records into the data frame and the code was not aware if the two endpoints are the same; I modified pypath.omnipath.export to generate only one record for loops; this will take effect at the next update of the server.

- **Lower number of PPI:** at building OmniPath we remove the undirected interactions supported only by references which support more than one interaction. This is a radical measure to lower the size of the network hopefully resulting a less noisy network because exactly those interactions have lower value in our applications and are anyways lower confidence. Until end of January the pypath.core.interaction.Interaction.is_directed method had a bug falsely returning True for undirected interactions hence the filtering mentioned above didn't work. The new contents of the web service are correct, we have 83,419 interactions in OmniPath. Also we see we remove actually ~30k undirected interactions in this step, it's not too much.

A new update of the webserver will take place during this week or beginning of the next week. 

Best,
Alberto.
