### ISSUE TITLE
Installation errors for windows

### ISSUE THREAD

**Issue by PauBadiaM** [saezlab/OmnipathR#54]
Hi @deeenes,

decoupleR [GitHub actions](https://github.com/saezlab/decoupleR/actions/runs/3882127815/jobs/6625972480#step:15:250) are failing in windows (the other OS are fine) due to installation issues with OmnipathR. Do you have any idea what could be triggering this? Thanks!

**Comment by deeenes** [comment]
Hi Pau,

The current version of OmnipathR is `3.6.*` (BioC 3.16) or `3.7.*` (BioC 3.17). Here it installs a version from 2021:

```
OmnipathR (NA -> 3.2.8) [CRAN]
Installing 1 packages: OmnipathR
Installing package into 'D:/a/_temp/Library'
(as 'lib' is unspecified)

  There is a binary version available but the source version is later:
          binary source needs_compilation
OmnipathR  3.2.0  3.2.8             FALSE

installing the source package 'OmnipathR'

trying URL 'https://bioconductor.org/packages/3.14/bioc/src/contrib/OmnipathR_3.2.8.tar.gz'
Content type 'application/octet-stream' length 2248[36](https://github.com/saezlab/decoupleR/actions/runs/3882127815/jobs/6625972480#step:15:37)7 bytes (2.1 MB)
```

You can update the BioC version [here](https://github.com/saezlab/decoupleR/blob/b57e5f7edd7bb4097860258c61eeaaa95270fc53/.github/workflows/check-bioc.yml#L54), though it's hardcoded at many other points in the action file.

Then the reason of the error is missing `purrr`. OmnipathR 2021 autumn [already had `purrr` as a dependency](https://github.com/saezlab/OmnipathR/blob/127afeee921b73bbfe89888d12b085fe0a34058c/DESCRIPTION#L58), probably the package is installed on the Windows build server, but fails to load its main shared object (dll):

```
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: Error: package or namespace load failed for 'OmnipathR' in library.dynam(lib, package, package.lib):
*** arch - x64
 DLL 'purrr' not found: maybe not installed for this architecture?
Error: Error: loading failed
Execution halted
ERROR: loading failed for 'i386'
* removing 'D:/a/_temp/Library/OmnipathR'
```

Also note that the issue is reported for `i386` arch only. It suggests you should just disable that architecture, I can't imagine anyone runs Decoupler on such an ancient machine. According to [this answer](https://github.com/rstudio/renv/issues/162#issuecomment-524005933), you could pass the `--no-multiarch` switch to `R CMD INSTALL` ([here](https://github.com/saezlab/decoupleR/blob/b57e5f7edd7bb4097860258c61eeaaa95270fc53/.github/workflows/check-bioc.yml#L249)). To achieve the same effect with `install.packages` or any `remotes` function, you can pass `INSTALL_opts = '--no-multiarch'`.

Best,

Denes

**Comment by PauBadiaM** [comment]
Thanks for the suggestions @deeenes! It seems to work, but now the problem is that the Omnipath server is down (I tried it both in R and Python)

**Comment by deeenes** [comment]
Yes, sorry, now the server is up again :)
