### ISSUE TITLE
PPI resources in omnipath

### ISSUE THREAD

**Issue by cgeyskens** [saezlab/OmnipathR#59]
Dear,

First of all, I would like thank you for this amazing resource which has helped me a lot in my research.

I'm using the import_all_interactions function in OmnipathR to look for interactors of my protein of interest. One of the main databases that I was using before is BioGRID, which is one of the resources of omnipath. But when I compared the interactors of my protein between manually querying BioGRID and the filtered interactors of the import_all_interactions function of Omnipath, I found that many interactors in BioGRID weren't included in the import_all_interactions. Also, the command below only gives around 2400 interactors and BioGRID says that it contains over 1 million interactions. So my first guess is that BioGRID is not updated in omnipath? I'm relatively new to R, so maybe I'm filtering wrong or I'm missing something.

all_interactions_human <- import_all_interactions(organism = 9606, resources = "BioGRID")

Thank you in advance!

**Comment by deeenes** [comment]
Hello,

I am glad to hear you find our software useful! :) 

About BioGRID, IntAct, InnateDB, HPRD, STRING and all similar ones: these are enormous collections of undirected PPI, largely from high-throughput screens, such as Y2H or AP-MS. We sometimes simply call these "interaction" resources, in contrast to "pathway" or "activity flow" resources, primarily referring to the first being undirected and the second is directed and with effect signs; the former doesn't include causality information, while the latter does.

In OmniPath networks, our main focus is on causal interactions. The `interactions` query doesn't return undirected interactions at all, and returns only a few if you add the `directed=no` or `directed = FALSE` (in R) parameter. It's not our aim to redistribute all data from these huge databases, as they already do an excellent work, offering many standard formats and supporting software.

Then you may ask, why these resources are here at all? Because they provide more literature references for existing interactions. We just want to tell the users that a causal interaction from e.g. SIGNOR has some confirming evidence also from BioGRID.

You can read more about the network resources and datasets in OmniPath [here](https://pypath.omnipathdb.org/notebooks/manual.html#Which-network-datasets-are-pre-defined-in-pypath?),  [here](https://r.omnipathdb.org/articles/bioc_workshop.html#networks) and [in the supplement of our first paper](https://static-content.springer.com/esm/art%3A10.1038%2Fnmeth.4077/MediaObjects/41592_2016_BFnmeth4077_MOESM495_ESM.pdf) you can get a detailed insight into the above mentioned categories.

I hope this helps.

Best,

Denes

**Comment by cgeyskens** [comment]
Hi Denes,

Thanks for the elaborate and quick answer, this helps.
