### ISSUE TITLE
OmniPath Interactions Sources

### ISSUE THREAD

**Issue by tam022** [saezlab/OmnipathR#64]
Hi OmniPath team,

I'm currently using the Web Service to retrieve some Interactions from the Omnipath dataset and had a question regarding the "sources" column. 
There are several interactions that are annotated with a combination of two databases. For example some interactions will have the sources **SIGNOR_ProtMapper** or **PhosphoSite_ProtMapper** while also including the distinct databases. There are also instances where the interaction contains the composite source such as **SIGNOR_ProtMapper** yet does not include the distinct database **SIGNOR**. I was wondering why some of the interactions where annotated in this way.

**Comment by deeenes** [comment]
Hello @tam022, `SIGNOR_ProtMapper` means OmniPath took the interaction from ProtMapper, which got it from SIGNOR originally. Logically, because OmniPath also directly integrates SIGNOR, this interaction should be also annotated with SIGNOR among its sources. If this is not the case, that's probably a small inconsistency, either a normal design consequence or a mistake. In either case, it can be the responsibility of data processing in OmniPath, or in ProtMapper. If you see such cases a lot, or you're really curious about it, I can look deeper into it.
