### ISSUE TITLE
Error Installing OmnipathR when trying to install liana

### ISSUE THREAD

**Issue by rstorch01** [saezlab/OmnipathR#80]
Hello,

I am getting an error running remotes::install_github('saezlab/liana'):

* installing *source* package ‘OmnipathR’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object ‘join_by’ is not exported by 'namespace:dplyr'
Execution halted
ERROR: lazy loading failed for package ‘OmnipathR’
* removing ‘/usr/local/R/4.0.2/lib64/R/library/OmnipathR’
Downloading GitHub repo saezlab/OmnipathR@HEAD
Skipping OmnipathR, it is already being installed
   checking for file ‘/tmp/RtmpbHkfqa/remotes6c692bf1f617/saezlab-liana-86adaca/DES✔  checking for file ‘/tmp/RtmpbHkfqa/remotes6c692bf1f617/saezlab-liana-86adaca/DESCRIPTION’
─  preparing ‘liana’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘liana_0.1.12.tar.gz’

ERROR: dependency ‘OmnipathR’ is not available for package ‘liana’

Please let me know if there is something else I need to do to get this to load successfully.  Thank you.

**Comment by deeenes** [comment]
Hi,

Sorry for the late answer, somehow this one got lost during holidays. The error says when the installer checks if `OmnipathR` can be loaded, it has to load also the `join_by` function from `dplyr`, which exists only in `dplyr` [since version 1.1.0](https://dplyr.tidyverse.org/news/index.html#dplyr-110). Most likely your `dplyr` is older than that, you can update it by `install_packages('dplyr')`.

To resolve the issue I also set a minimum version for `dplyr` (7d148f9), so it's enough if you do `remotes::install_github('OmnipathR')`
